controller_list:
  - name: fake_lwr_arm_controller
    joints:
      - lwr_arm_0_joint
      - lwr_arm_1_joint
      - lwr_arm_2_joint
      - lwr_arm_3_joint
      - lwr_arm_4_joint
      - lwr_arm_5_joint
      - lwr_arm_6_joint